version: "3.9"
services:
  api:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      dockerfile: Dockerfile.dev
      context: .
      target: development
    command: npm run start:dev
    depends_on:
      - mongo-db
    ports:
      - "3000:3000"
    links:
      - mongo-db 
    volumes:
      - .:/app
      - /app/node_modules
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=xantx
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

