#Delete project

DELETE http://localhost:3000/api-project-manager/v1/projects/641269d94b7ba33663daaa15

# Get all projects

GET http://localhost:3000/api-project-manager/v1/projects

# Update project

PATCH http://localhost:3000/api-project-manager/v1/projects/641271dc41f1c66cd54a4ea5
Content-Type: application/json

{
  "title": "Modified title",
  "description": "Modifies description"
}

# Save a project
POST http://localhost:3000/api-project-manager/v1/projects
Content-Type: application/json

{
  "title": "Example project",
  "description": "aaaaaaaaaaa"
}
