#Delete project

DELETE http://localhost:3000/api-project-manager/v1/projects/6417a02cbd89a32488edeb3d

# Get all projects

GET http://localhost:3000/api-project-manager/v1/projects

# Update project

PATCH http://localhost:3000/api-project-manager/v1/projects/641271dc41f1c66cd54a4ea5
Content-Type: application/json

{
  "title": "Modified title",
  "description": "Modifies description"
}

# Save a project
POST http://localhost:3000/api-project-manager/v1/projects
Content-Type: application/json

{
  "title": "Ejemplo de proyecto 1",
  "description": "variante de documento"
}
